# Generated by Django 5.1.6 on 2025-03-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_alter_event_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(help_text='FontAwesome or Flaticon class name', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='themes/')),
                ('url', models.CharField(default='/event', max_length=255)),
            ],
        ),
    ]
