# Generated by Django 5.1.6 on 2025-03-03 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_eventdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventDetail',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
