# Generated by Django 5.1.6 on 2025-03-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_delete_eventdetail_delete_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcategory',
            name='description',
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
