# Generated by Django 5.1.6 on 2025-03-25 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0011_payment_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order_id',
        ),
    ]
