# Generated by Django 5.1.6 on 2025-03-25 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0013_payment_order_id_payment_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_status',
        ),
    ]
