# Generated by Django 5.1.2 on 2025-03-26 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0014_remove_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.eventcategory'),
        ),
    ]
