# Generated by Django 5.0.6 on 2025-03-27 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0015_plan_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plan_images/')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Customer.plan')),
            ],
        ),
    ]
