# Generated by Django 5.0.6 on 2025-04-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0016_planimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='event_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='event_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
