# Generated by Django 5.2 on 2025-04-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0019_remove_review_email_remove_review_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='review',
            name='event',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_date',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_text',
        ),
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='review',
            name='message',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default='username', max_length=255),
        ),
        migrations.AddField(
            model_name='review',
            name='phone',
            field=models.CharField(default='999999999', max_length=15),
        ),
        migrations.AddField(
            model_name='review',
            name='venue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
