# Generated by Django 5.2 on 2025-04-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0020_remove_review_customer_remove_review_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
